version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: luiff_postgres
    restart: always
    environment:
      POSTGRES_USER: luiff_user
      POSTGRES_PASSWORD: luiff_password
      POSTGRES_DB: luiff_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
