[variables]
HOSTNAME = "0.0.0.0"
PORT = "3000"
NODE_ENV = "production"

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "node .next/standalone/server.js"
